name: safeline_ku
description: Safe Line app

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/image/
    - assets/icon/
    - assets/icon/navbar/

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  url_launcher: ^6.1.10
  intl: 0.18.0
  dio: ^5.4.0
  dotenv: ^4.1.0
  flutter_dotenv: ^5.1.0
  logger: ^2.0.1
  flutter_svg: ^2.0.0+1
  fluttertoast: ^8.1.2
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.0
  google_maps_flutter: ^2.5.3
  geolocator: ^7.0.3
  http: ^1.2.0
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
